# Tensor 생성
- 파이토치에서 데이터를 저장하는 자료구조
- ndarray와 성격, 사용법이 유사하다.

> **pytorch의 tensor는 숫자 데이터 타입만 지원한다.**

##  원하는 형태(shape) 텐서 생성
- **torch.tensor(자료구조 \[, dtype\])**
    - 지정한 dtype(Data type)에 맞는 Tensor객체를 생성해서 반환한다.
      
## 특정 타입의 Tensor를 직접 생성
- torch.tensor()로 생성하면서 dtype을 지정하면 아래 타입의 Tensor객체가 생성된다. 지정안하면 알아서 자동 설정
- 원하는 Type의 Tensor클래스를 이용해 직접 생성해도 된다.
- **torch.FloatTensor(자료구조)**
    - float32 타입 텐서 생성
- **torch.LongTensor(자료구조)** 
    - int64 타입 텐서생성
- 그외
    - BoolTensor(bool), CharTensor(int8), ShortTensor(int16), IntTensor(int32), DoubleTensor(float64)
    
## tensor 상태 조회
- **tensor.shape, tensor.size(\[축번호\])**
    -  tensor의 shape조회 / size의 경우 메소드야.
- **tensor.dtype, tensor.type()**
    - tensor 원소들의 데이터타입 조회
    - dtype은 **data type**을 type()은 tensor **객체의 클래스 타입**을 반환한다.
- **tensor.ndim, tensor.dim()**  : tensor 차원
- **tensor.numel()**: 전체 차원에 대한 모든 원소 개수



In [1]:
import torch
import numpy as np

In [ ]:
# ndarray로 먼저 보자
np.array([1, 2, 3], dtype=np.int8)#"int8") # ndarray에서만 문자열로 넣을 수 있어.

array([1, 2, 3], dtype=int8)

In [8]:
print('torch Data types')
# 그냥 pytorch 자체에 존재하는 데이터 타입 클래스 
print("float", torch.float16, torch.float32, torch.float64, torch.float, torch.double, sep=' | ')  #torch.float: float32 / 가장 많이 사용 
print("int:", torch.int8, torch.int16, torch.int32, torch.int64, torch.short, torch.int, torch.long, sep=' | ') # 가능 / int8은 따로 없어 
print("uint:", torch.uint8, torch.uint16, torch.uint32, torch.uint64, sep=' | ')
print("bool:", torch.bool)

torch Data types
float | torch.float16 | torch.float32 | torch.float64 | torch.float32 | torch.float64
int: | torch.int8 | torch.int16 | torch.int32 | torch.int64 | torch.int16 | torch.int32 | torch.int64
uint: | torch.uint8 | torch.uint16 | torch.uint32 | torch.uint64
bool: torch.bool


In [ ]:
a = torch.tensor([[1,2],[3,4]], dtype=torch.float32) # 여기 문자열로 못 들어가 


print("shape:", a.shape, a.size()) # 얘네 둘 아예 같은 값 반환 / torch.Size라는 내부 attribute을 불러오는거야 
print("0축 크기:", a.shape[0], a.size(0))
print("type:", a.type(), a.dtype)  # type(): Tensor 객체 타입. dtype: data type => 둘은 좀 다르다.
print('차원크기:', a.dim(), a.ndim)
print('원소개수:', a.numel())
print("device:", a.device)  # tensor를 다루는 processor(메모리위치) - cpu, cuda(gpu)
### CPU와 GPU는 각각 연산할 데이터 저장공간인 RAM, VRAM에서만 데이터를 가져다 사용할 수 있다.

shape: torch.Size([2, 2]) torch.Size([2, 2])
0축 크기: 2 2
type: torch.FloatTensor torch.float32
차원크기: 2 2
원소개수: 4
device: cpu


In [11]:
aa = torch.tensor(range(10))
print(aa)
aa.type()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


'torch.LongTensor'

In [18]:
#Float, Double(32, 64bit 실수)/Int, Long(32, 64 bit 정수) type Tensor
### 특정 값을 표현하는 float의 경우 메모리 효율성을 위해 기본적으로 32비트를 사용하지만
### index등처럼 매우 커질 수 있는 int의 경우 기본적으로 64비트를 사용하게 된다.
b = torch.FloatTensor([1,3,7])  #float32
print(b.dtype)
# c = torch.IntTensor([10,20,30])    # int32
# print(c.dtype)
# d = torch.DoubleTensor([1, 2, 3])  # float64
# print(d.dtype)
# e = torch.LongTensor([10, 20, 30]) # int64
# print(e.dtype)

torch.float32


## 동일한 값을 원소로 가지는 Tensor 생성
- **torch.zeros(\*size), zeros_like(텐서)**: 0으로 구성된 tensor 생성
- **torch.ones(\*size), ones_like(텐서)**: 1로 구성된 tensor생성
- **torch.full(size, fill_value), full_like(텐서, fill_value)**: 지정한 값으로 구성된 tensor생성
  - size 
    - shape을 지정한다.
    - zeros, ones는 가변인자이므로 축별 size를 순서대로 서정
    - full 은 tuple/list로 shape을 지정한다. -> 뒤에 fill_value 를 따로 받아야하니까 당연하지
    

In [19]:
a = torch.zeros(3,2,3) # 3 x 2 x 3
a.dtype
# torch.ones(2,3)  # 2 X 3
# torch.full([3,2], fill_value=100) # 3 x 2


torch.float32

In [20]:
# 특정 배열과 동일한 shape의 tensor 생성.
a = torch.tensor([[1, 2],[3, 4]]) # 2 x 2

print(a.shape)
b = torch.zeros_like(a)  # a와 같은 shape, dtype 으로 생성.
# b = torch.ones_like(a)
# b = torch.full_like(a, 20)
print(b.shape, b.dtype, a.dtype)
b

torch.Size([2, 2])
torch.Size([2, 2]) torch.int64 torch.int64


tensor([[0, 0],
        [0, 0]])

## 동일한 간격으로 떨어진 값들로 구성된 배열생성
- **torch.arange(start=0, end, step=1)** 
- **torch.linspace(start, end, steps,)** : steps - 원소개수

In [ ]:
torch.arange(10)  # end. 0 ~ 10-1 1씩 증가
# torch.arange(0, 1, 0.1) # 0 ~ 1-0.1, 0.1 
# torch.arange(10, 1, -1) # 10 ~ 1-(-1), -1 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# linespace의 경우 기본적으로 분위수를 계산하기에 자동 float 인식 ! 
torch.linspace(0, 10, 5) # 0 ~ 10, 5개원소
torch.linspace(0, 1, 11)


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000])

## 빈 tensor 생성
- **torch.empty(\*size)**

In [54]:
torch.empty(3,2,7) # 3 X 2 X 7

tensor([[[-1.2570e+24,  1.5484e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
           0.0000e+00,  0.0000e+00]]])

## 난수를 이용한 생성

- **torch.rand(\*size)**: 0 ~ 1사이 실수로 구성된 배열을 생성. 각 값은 균등분포를 따른다.
- **torch.randn(\*size)**: 표준정규분포(평균:0, 표준편차:1)를 따르는 실수로 구성된 배열 생성
- **torch.randint(low=0, high, size)**: 지정한 범위의 정수로 구성된 배열 생성
- **torch.randperm(n)**: 0 ~ n-1 사이의 정수를 랜덤하게 섞은 값을 원소로 가지는 배열 생성

In [ ]:
#torch.manual_seed(0)  # seed 설정
torch.rand(1, 3, 5) # 100 x 3 x 5 / 0~1 실수
torch.randn(30, 3) # 30 X 3 / 표준정규분포 실수 -> 당연히 실수밖에 없어
torch.randint(1, 100, (3, 3, 6))  # rand의 정수 버전. 구간도 정해줘야해 
torch.randperm(100) # 0 ~ 99 를 섞어서 구성 -> randint의 편의성 버전으로 index 생성 등에 유용하게 사용할 수 있다.

tensor([76, 30, 98, 38, 89, 72, 47, 77, 66, 27, 64, 85, 36, 71, 22, 16, 31, 35,
        67, 42, 94, 95, 25, 53, 90, 54, 13,  6,  9, 43, 59, 87, 97, 69, 86, 60,
        63, 52, 34, 12, 26,  2, 58, 68, 28,  7, 32, 55, 61, 29, 15, 17, 49, 65,
        10, 57, 73, 78, 83,  5,  0, 21,  4,  3, 51, 18, 84, 75, 40, 56, 33, 91,
        70, 11, 93,  8, 23,  1, 24, 80, 14, 44, 82, 39, 41, 19, 50, 46, 81, 92,
        62, 20, 37, 74, 96, 45, 88, 79, 99, 48])

In [99]:
a = torch.arange(100)
a
# a 섞기
idx = torch.randperm(100) # 0 ~ 99 섞어서 반환. -> index
idx
b = a[idx] # tensor로 fancy indexing이 가능해 !@

In [100]:
b[0] = 999
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Tensor gpu/cpu 메모리로 옮기기

- pytorch는 데이터셋인 tensor를 cpu메모리와 gpu 메모리로 서로 옮길 수 있다.
    - 데이터에 대한 연산처리를 어디서 하느냐에 따라 메모리를 선택한다.
    - 장치는 문자열로 설정한다.
        - CPU 사용: "cpu"
        - nvida GPU: "cuda"
        - Apple m1: "mps"
            - pytorch 1.12 부터 지원
- 옮기기
    - tensor 생성시 `device` 파라미터를 이용해 설정
    - `tensor.to(device)`를 이용해 설정
- 현재 실행환경에서 어떤 장비를 사용할 수 있는지 확인
    - nvidia gpu 사용가능확인
        - `torch.cuda.is_available()` - nvida gpu 사용가능 여부
        - `torch.backends.mps.is_available()` - M1 사용가능 여부

In [ ]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# device = 'mps' if torch.backends.mps.is_available() else 'cpu'
# device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
device, torch.cuda.is_available()

('cpu', False)

In [104]:
t = torch.tensor([1, 2, 3], dtype=torch.float32, device=device) #생성할 때 device 지정.
print(t, t.device) # tensor가 어느 device에 있는지 확인 / tensor(데이터)의 attribute으로 당연히 .device가 존재해 

tensor([1., 2., 3.]) cpu


In [ ]:
t2 = t.to("cpu")  # 다른 device로 옮기기.
print(t2, t2.device)

tensor([1., 2., 3.]) cpu


## tensor를 상수로 변환
- torch.Tensor객체를 파이썬 상수로 변환.
- tensor객체.item()
    - Scalar(상수) 또는 원소가 하나인 tensor를 python 상수로 변환

In [109]:
print(torch.tensor(30)) 

tensor(30)


In [114]:
a = torch.tensor(10)  # 상수(scalar) => 0차원 Tensor
print(a, a.ndim)
print(a.item())
print(type(a), type(a.item()))

tensor(10) 0
10
<class 'torch.Tensor'> <class 'int'>


In [117]:
b = torch.tensor([[20]]) # 원소(tensor.numel)가 하나인 N차원 배열
print(b, b.dim())
print(b.item()) #원소가 하나인 배열(텐서) 변환 가능

tensor([[20]]) 2
20


In [116]:
c = torch.tensor([1, 10, 100])
print(c)
# print(c.item()) #원소가 여러개일 경우 Exception발생

tensor([  1,  10, 100])


In [ ]:
d = torch.tensor([10], device='cuda')
print(d)
print(d.item())

## ndarray 호환

- ndarray를 tensor로 생성
    - **torch.tensor(ndarray)**
    - **torch.from_numpy(ndarray)**
- tensor를 ndarray로 변환
    - **tensor.numpy()**
    - tensor가 gpu에 있을 경우 cpu로 옮긴 뒤 변환해야 한다.

In [118]:
import numpy as np
import torch

In [122]:
# ndarray -> tensor
arr = np.arange(1,10)

torch.tensor(arr, dtype=torch.float32)
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
# tensor -> ndarray
t = torch.randn(3,3)
print(t)
t.to("cpu").numpy()

tensor([[-0.8768,  0.0489,  0.2569],
        [ 0.1613, -0.3723, -0.7986],
        [-0.9558,  1.4270,  0.5392]])


array([[-0.87683207,  0.04889311,  0.2569108 ],
       [ 0.16125256, -0.37231404, -0.79860973],
       [-0.95579004,  1.4270319 ,  0.53921014]], dtype=float32)

In [ ]:
t2 = torch.randn(2,2, device="cuda")
t2

In [ ]:
t2.numpy() 
# t2.to("cpu").numpy()

# 원소 조회및 변경 

## indexing/slicing

- 대부분 Numpy 와 동일
    - **slicing에서 step을 <u>음수로 지정할 수 없다.</u>**
    - Tensor의 경우 효율적인 순차적 메모리구조를 사용하기 때문이다.

In [ ]:
t = torch.randint(-10, 10, (100, )) # 일차원은 지정을 해주어야해 
t

tensor([  1,  -2,   0,   1,   0,  -5,   6,   5,  -7,  -8,   1,  -9,  -6,   0,
        -10,  -5,   9,  -3,   3,   0,  -1,  -1,  -1,  -6,  -4,  -8,   7,   7,
         -2,   8,  -2,   8,   0,  -6, -10,   5,   7,   1,  -3,  -3,   8,   3,
          0,  -5,  -1,  -4,  -5,   6,   5,   2,   7,   8,  -4,   8,  -1, -10,
          7,   5,   9,   9,  -3,  -2,   7,  -5,  -8,  -2,   3,   6,  -9, -10,
         -5,  -2,   4,  -7, -10,  -1,  -7,   2,   3,   8,  -4,  -9,  -6,   9,
          5,  -1, -10,   9,   2,   1,  -3,  -8,   3,  -2,   5,   6,   2,   3,
          5,  -5])

In [128]:
t[0]
# t[[1, 5, -1]] # 여러개 조회-> fancy indexing

tensor(1)

In [130]:
t[:5]
# t[10:15]
# t[90:]
# t[3:30:3]

####### step 음수 안된다. 그래서 reverse(역순 조회)가 안됨. reverse하려면 flip() 사용
# t[10:1:-2]  
# t[1:10:2].flip(dims=(0,)) #reverse 축 정해주기 

tensor([ 1, -2,  0,  1,  0])

In [131]:
t[1:10:2]

tensor([-2,  1, -5,  5, -8])

## boolean index
- 논리 연산은 &, |, ~ 을 사용한다.

In [134]:
# boolean index
t[t > 0]
t>0

tensor([ True, False, False,  True, False, False,  True,  True, False, False,
         True, False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False,  True,  True, False,  True,
        False,  True, False, False, False,  True,  True,  True, False, False,
         True,  True, False, False, False, False, False,  True,  True,  True,
         True,  True, False,  True, False, False,  True,  True,  True,  True,
        False, False,  True, False, False, False,  True,  True, False, False,
        False, False,  True, False, False, False, False,  True,  True,  True,
        False, False, False,  True,  True, False, False,  True,  True,  True,
        False, False,  True, False,  True,  True,  True,  True,  True, False])

In [135]:
t[(t > 0) & (t < 5)]

tensor([1, 1, 1, 3, 1, 3, 2, 3, 4, 2, 3, 2, 1, 3, 2, 3])

In [136]:
# boolean index 처리 함수.
t.masked_select(t > 0)

tensor([1, 1, 6, 5, 1, 9, 3, 7, 7, 8, 8, 5, 7, 1, 8, 3, 6, 5, 2, 7, 8, 8, 7, 5,
        9, 9, 7, 3, 6, 4, 2, 3, 8, 9, 5, 9, 2, 1, 3, 5, 6, 2, 3, 5])

In [137]:
t

tensor([  1,  -2,   0,   1,   0,  -5,   6,   5,  -7,  -8,   1,  -9,  -6,   0,
        -10,  -5,   9,  -3,   3,   0,  -1,  -1,  -1,  -6,  -4,  -8,   7,   7,
         -2,   8,  -2,   8,   0,  -6, -10,   5,   7,   1,  -3,  -3,   8,   3,
          0,  -5,  -1,  -4,  -5,   6,   5,   2,   7,   8,  -4,   8,  -1, -10,
          7,   5,   9,   9,  -3,  -2,   7,  -5,  -8,  -2,   3,   6,  -9, -10,
         -5,  -2,   4,  -7, -10,  -1,  -7,   2,   3,   8,  -4,  -9,  -6,   9,
          5,  -1, -10,   9,   2,   1,  -3,  -8,   3,  -2,   5,   6,   2,   3,
          5,  -5])

In [138]:
# 변경
t[0] = 100
t

tensor([100,  -2,   0,   1,   0,  -5,   6,   5,  -7,  -8,   1,  -9,  -6,   0,
        -10,  -5,   9,  -3,   3,   0,  -1,  -1,  -1,  -6,  -4,  -8,   7,   7,
         -2,   8,  -2,   8,   0,  -6, -10,   5,   7,   1,  -3,  -3,   8,   3,
          0,  -5,  -1,  -4,  -5,   6,   5,   2,   7,   8,  -4,   8,  -1, -10,
          7,   5,   9,   9,  -3,  -2,   7,  -5,  -8,  -2,   3,   6,  -9, -10,
         -5,  -2,   4,  -7, -10,  -1,  -7,   2,   3,   8,  -4,  -9,  -6,   9,
          5,  -1, -10,   9,   2,   1,  -3,  -8,   3,  -2,   5,   6,   2,   3,
          5,  -5])

In [139]:
t = torch.arange(1, 10).reshape(3,3)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [140]:
# t[ 0축, 1축 ]
t[1, 2].item()
t[0, 2].item()

3

In [ ]:
t[[1,0], [2,2]]  #(1,2), (0,2) # 마찬가지로 Fancy Indexing / DataFrame에서 했던 indexing이랑 같은 방식이야
# t[[첫번째값, 두번째값]-0축, [첫번째값, 두번째값]-1축]

tensor([6, 3])

# Reshape

## shape 변경
- tensor객체.reshape(\*shape) / ~~view(\*shape) 이용~~
    - 변환 후 값을 변경하면 원본 배열의 값도 같이 바뀐다. -> 방대한 양의 데이터를 다루는 Tensor의 특징 상 DataFrame과 다르게 원본을 계속 바꿔나가는 것이 기본값
 > tensor.clone(): tensor를 복제한다. # copy() 가 아니야@@@@@@

In [142]:
a=torch.rand(12) # 0~1
a2 = a.reshape(3,4)
a3 = a.reshape((3,2,2))
a4 = a.reshape((3,2,-1))  #한 개 axis는 -1로 설정가능하고 그럼 계산해서 알아서 설정해 준다.
print(a.shape, a2.size(), a3.shape, a4.shape)

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [143]:
a5 = a.view(3,4)
a6 = a.view((3,2,2))
a7 = a.view((3,2,-1))  #한개 axis는 -1로 설정가능
print(a.shape, a5.size(), a6.shape, a7.shape)

torch.Size([12]) torch.Size([3, 4]) torch.Size([3, 2, 2]) torch.Size([3, 2, 2])


In [144]:
# a5[0, 0] = 12.1
a2[0, 1] = 15.1

print(a2)

tensor([[ 0.8295, 15.1000,  0.8344,  0.2590],
        [ 0.1525,  0.0919,  0.2448,  0.2272],
        [ 0.7281,  0.1700,  0.4153,  0.3183]])


In [ ]:
# tensor복사: clone() 메소드
r = a.reshape(3, 4).clone()
r[0,0] = 100.1
print(a) # reshape에 의해서 변해있어 

tensor([ 0.8295, 15.1000,  0.8344,  0.2590,  0.1525,  0.0919,  0.2448,  0.2272,
         0.7281,  0.1700,  0.4153,  0.3183])


In [ ]:
r

## dummy 축 늘리기

- ~~None을 이용 (numpy의 newaxis 대신 None을 사용한다.)~~
- unsqueeze(dim=축번호)

In [158]:
import torch
a = torch.tensor([[10,20],[10,20]])
print(a.shape)

a1, a2 = a[None, :], a.unsqueeze(dim=0) # dim=정수만가능 / axis 변수와 비슷한 느낌이야 
print(a1.shape, a2.shape)

a3, a4 = a[:, :, None], a.unsqueeze(dim=-1)   # a[:, None] # 0축 :, 1축 None, 2번축 지정안함 -> 원래대로 그래서 (2, 1, 2) 가됨. / 이때는 :이 딱 하나의 축만을 의미 
print(a3.shape, a4.shape)

a5, a6 = a3[:,None,:,:, None],  a3.unsqueeze(dim=1)  # unsqueeze(): dim=정수만가능 (한번에 dummy축은 하나만 추가가능.)
print(a5.shape, a6.shape)

torch.Size([2, 2])
torch.Size([1, 2, 2]) torch.Size([1, 2, 2])
torch.Size([2, 2, 1]) torch.Size([2, 2, 1])
torch.Size([2, 1, 2, 1, 1]) torch.Size([2, 1, 2, 1])


## dummy 축 제거
- squeeze(\[dim=축번호\]) 이용
- 당연히 squeeze! 쥐어짜는거니까 dummy 축만 지워져 

In [162]:
t = torch.rand(3, 1, 4, 1, 5, 1)
print(t.shape)

r1 = t.squeeze()  #축을 명시 하지 않으면 모두 제거
print(r1.shape)

r2 = t.squeeze(dim=1) # 특정 axis 제거
print(r2.shape)

r3 = t.squeeze(dim=[1,3]) # 여러 axis의 dummy 축 제거
print(r3.shape)

torch.Size([3, 1, 4, 1, 5, 1])
torch.Size([3, 4, 5])
torch.Size([3, 4, 1, 5, 1])
torch.Size([3, 4, 5, 1])


# tensor 합치기
torch.cat([tensorA, tensorB, ...], dim=0) : 기준축 default 는 0

In [192]:
a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(20,30).reshape(2,5)
d = torch.arange(10,19).reshape(3,3)

In [193]:
torch.cat([a, b], dim=0) 

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [194]:
torch.cat([a, b, c], dim=0)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])

In [195]:
torch.cat([a, b], axis=1) # dim 대신 axis사용가능

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [196]:
torch.cat([a, b, c], axis=1)

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19, 25, 26, 27, 28, 29]])

In [176]:
torch.cat([a, b], axis=-1)  # -1: 마지막 axis

tensor([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [ ]:
a.shape, d.shape
# 합치는 기준축 이외의 축 size는 같아야 한다.
# torch.cat([a, d])  #dim=0, Error  1축 size가 달라서 Error

# 값의 위치(index) 변경
- tensor 원소의 index의 위치를 바꾼다.
- `tensor.transpose(axis1, axis2)` 
    - 두 축의 자리만 변경 할 수 있다.
- `tensor.permute(axis1, axis2, axis3, ..)`
    - 두 개 이상의 축 자리를 변경한다.

In [189]:
X = torch.arange(24).reshape(2, 3, 4)
print(X.shape)

y = X.transpose(1, 2) # 마찬가지로 참조 관계가 형성돼 
y[0, 0] = 999
print(y.shape, y, X)

z = X.permute(2, 0, 1)
print(z.shape)

torch.Size([2, 3, 4])
torch.Size([2, 4, 3]) tensor([[[999, 999, 999],
         [  1,   5,   9],
         [  2,   6,  10],
         [  3,   7,  11]],

        [[ 12,  16,  20],
         [ 13,  17,  21],
         [ 14,  18,  22],
         [ 15,  19,  23]]]) tensor([[[999,   1,   2,   3],
         [999,   5,   6,   7],
         [999,   9,  10,  11]],

        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]])
torch.Size([4, 2, 3])


# tensor 연산 및 주요 함수

## element-wise 연산
- tensor와 상수 연산시, tensor와 tensor간 연산시 원소별로 처리한다.
- 행렬곱 연산을 제외하고 tensor간 연산시 피연산자 tensor간에 shape이 같아야 한다.
    - shape이 다를 경우 조건이 맞으면 broadcasting을 한 뒤에 연산한다. (size가 다른 축의 경우 한개의 피연산자 size가 1일 경우 복사하여 shape을 맞춘다.)
    

In [197]:
import torch

a = torch.arange(10).reshape(2,5)
b = torch.arange(10,20).reshape(2,5)
c = torch.arange(50, 55)

print(a)
print(b)
print(c)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([50, 51, 52, 53, 54])


In [198]:
print(a + 100)
print(a - 100)
print(a < 5)

tensor([[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109]])
tensor([[-100,  -99,  -98,  -97,  -96],
        [ -95,  -94,  -93,  -92,  -91]])
tensor([[ True,  True,  True,  True,  True],
        [False, False, False, False, False]])


In [199]:
print(a + b)
print(a == b)

tensor([[10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False]])


In [200]:
a.size(), c.size()

(torch.Size([2, 5]), torch.Size([5]))

In [201]:
# broadcasting
print(a + c)

tensor([[50, 52, 54, 56, 58],
        [55, 57, 59, 61, 63]])


## 주요 연산함수

### 주요 상수
#### 자연상수 E

In [203]:
torch.e, np.e, torch.pi, np.pi

(2.718281828459045, 2.718281828459045, 3.141592653589793, 3.141592653589793)

#### torch.nan, torch.inf
- nan: Not a Number, 주로 결측치를 표현한다. / 여기서는 na 아니야....
- inf: infinit 무한. 
    - torch.inf: 양의 무한
    - -torch.inf: 음의 무한
- torch.isnan(tensor)
    - 원소별 결측치 확인
- torch.isinf(tensor)    
    - 원소별 inf 확인

In [204]:
print(torch.inf > 10000000000000000, torch.inf < 10000000000)
print(-torch.inf < -1000000000000000000000, -torch.inf > 10)


True False
True False


In [206]:
print(torch.log(torch.tensor(-1))) # nan (계산결과가 없으므로-없는값-nan 반환)
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4])))  # nan 여부 확인
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf])))  # inf 여부 확인

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


## 주요 연산 함수

In [207]:
x=torch.arange(-4, 5).reshape(3,3)
print(x)
print(torch.abs(x)) # 절대값 
print(torch.sqrt(torch.abs(x))) #  제곱근
print(torch.exp(x))  # torch.e**x
print(torch.log(torch.abs(x)))
print(torch.log(torch.exp(torch.tensor(1))))  # torch.log() 밑이 e인 로그계산
print(torch.log10(torch.tensor(10)))         # torch.log10() 밑이 10인 로그계산
print(torch.log2(torch.tensor(2)))           # torch.log2() 밑이 2인 로그계산

tensor([[-4, -3, -2],
        [-1,  0,  1],
        [ 2,  3,  4]])
tensor([[4, 3, 2],
        [1, 0, 1],
        [2, 3, 4]])
tensor([[2.0000, 1.7321, 1.4142],
        [1.0000, 0.0000, 1.0000],
        [1.4142, 1.7321, 2.0000]])
tensor([[1.8316e-02, 4.9787e-02, 1.3534e-01],
        [3.6788e-01, 1.0000e+00, 2.7183e+00],
        [7.3891e+00, 2.0086e+01, 5.4598e+01]])
tensor([[1.3863, 1.0986, 0.6931],
        [0.0000,   -inf, 0.0000],
        [0.6931, 1.0986, 1.3863]])
tensor(1.)
tensor(1.)
tensor(1.)


In [ ]:
y = x + torch.randn((3,3)) # 정규분포 
print(y)
print(torch.round(y)) # 반올림
print(torch.round(y, decimals=2)) # 소수점 둘째자리 이하에서 반올림 / 음수부는 정수 부분을 의미 
print(torch.floor(y)) # 내림
print(torch.ceil(y)) # 올림

tensor([[-4.0594, -3.3733, -0.8710],
        [-0.0471, -1.9334,  1.7485],
        [ 1.9152,  2.7192,  2.0084]])
tensor([[-4., -3., -1.],
        [-0., -2.,  2.],
        [ 2.,  3.,  2.]])
tensor([[-4.0600, -3.3700, -0.8700],
        [-0.0500, -1.9300,  1.7500],
        [ 1.9200,  2.7200,  2.0100]])
tensor([[-5., -4., -1.],
        [-1., -2.,  1.],
        [ 1.,  2.,  2.]])
tensor([[-4., -3., -0.],
        [-0., -1.,  2.],
        [ 2.,  3.,  3.]])


### 행렬곱
- `@` 연산자 또는 `torch.matmul(tensor1, tensor2)` 함수 이용

In [212]:
import torch

In [221]:
x = torch.FloatTensor([[1, 2],[3, 4],[5, 6]])

y = torch.FloatTensor([[1, 2],[1, 2],])
x.size(), y.shape

(torch.Size([3, 2]), torch.Size([2, 2]))

In [222]:
z1 = x @ y
z2 = torch.matmul(x, y) # matrix
print(z1.shape, z2.shape)
print(z1)
print(z2)

torch.Size([3, 2]) torch.Size([3, 2])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])
tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])


In [ ]:
# Batch 행렬곱(Batch matrix muliplication) - bmm() / batch 란 작은 데이터셋 묶음을 말한다.
# 피연산자로 두개의 3차원 tensor를 axis (1, 2)를 기준으로 행렬곱을 처리한다.
import torch
x = torch.FloatTensor(3,4,2) # 앞에가 살아
y = torch.FloatTensor(3,2,6) # 뒤에가 살아 
z = torch.bmm(x, y)
z.shape 


torch.Size([3, 4, 6])

## 기술통계함수

In [224]:
X=torch.randn(3,4)
print(X)

tensor([[-0.5840, -1.2884,  2.3136, -1.5283],
        [ 0.6884,  0.7363,  0.8479, -0.6382],
        [ 0.1937,  0.9737, -1.7355,  1.4347]])


In [ ]:
print(torch.sum(X))  # default: 전체기준으로 계산. dim=None
print(torch.sum(X, dim=1)) #dim/axis 지정: 지정한 axis의 index가 다른 값끼리 계산.
print(torch.sum(X, dim=1, keepdims=True)) # 기술통계함수들을 실행하면 차원이 줄어든다(dummy 제거). keepdims=True로 하면 차원유지

tensor(1.4139)
tensor([-1.0872,  1.6344,  0.8667])
tensor([[-1.0872],
        [ 1.6344],
        [ 0.8667]])


In [226]:
print(torch.mean(X))
print(torch.mean(X, dim=0))
print(torch.mean(X, dim=0, keepdims=True))

tensor(0.1178)
tensor([ 0.0993,  0.1405,  0.4754, -0.2439])
tensor([[ 0.0993,  0.1405,  0.4754, -0.2439]])


In [227]:
print(torch.std(X)) # standard deviation 표준 편차
print(torch.var(X)) # variance
print(torch.var(X, dim=0))

tensor(1.2693)
tensor(1.6110)
tensor([0.4114, 1.5456, 4.2029, 2.3114])


In [228]:
# tensor.메소드() 
print(X.sum(dim=1, keepdims=True))
print(X.mean(dim=1, keepdims=True))
print(X.std())

tensor([[-1.0872],
        [ 1.6344],
        [ 0.8667]])
tensor([[-0.2718],
        [ 0.4086],
        [ 0.2167]])
tensor(1.2693)


In [229]:
X

tensor([[-0.5840, -1.2884,  2.3136, -1.5283],
        [ 0.6884,  0.7363,  0.8479, -0.6382],
        [ 0.1937,  0.9737, -1.7355,  1.4347]])

In [ ]:
# 다차원의 데이터기에 max/min의 경우 별도의 반환용 객체가 존재하는 것 ! 
print(torch.max(X)) # 전체 기준 max값 계산.
print(torch.max(X, dim=0))  # 축을 지정하면 return_types.max 타입객체로 반환. max값과 max값의 해당 축 기준 index를 묶어서 반환
print(torch.max(X, dim=1))
print(torch.max(X, dim=1).values, torch.max(X, dim=1).indices, sep=" || ")


print(torch.max(X, dim=0, keepdims=True))  #keepdims=True : 차원(rank)를 유지
print(torch.max(X, dim=1, keepdims=True)) # 이 경우 차원유지가 티가 많이 나 

tensor(2.3136)
torch.return_types.max(
values=tensor([0.6884, 0.9737, 2.3136, 1.4347]),
indices=tensor([1, 2, 0, 2]))
torch.return_types.max(
values=tensor([2.3136, 0.8479, 1.4347]),
indices=tensor([2, 2, 3]))
tensor([2.3136, 0.8479, 1.4347]) || tensor([2, 2, 3])
torch.return_types.max(
values=tensor([[0.6884, 0.9737, 2.3136, 1.4347]]),
indices=tensor([[1, 2, 0, 2]]))
torch.return_types.max(
values=tensor([[2.3136],
        [0.8479],
        [1.4347]]),
indices=tensor([[2],
        [2],
        [3]]))


In [238]:
print(torch.min(X))
print(torch.min(X, dim=0)) # return_types.min 타입객체로 반환. min값과 min값의 index를 묶어서 반환
print(torch.min(X, dim=1))

tensor(-1.7355)
torch.return_types.min(
values=tensor([-0.5840, -1.2884, -1.7355, -1.5283]),
indices=tensor([0, 0, 2, 0]))
torch.return_types.min(
values=tensor([-1.5283, -0.6382, -1.7355]),
indices=tensor([3, 3, 2]))


In [ ]:
# torch.max.indices 랑 같은 역할이야 
print(torch.argmax(X)) # 평탄화 기준 index 
print(torch.argmax(X, dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(X, dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor(2)
tensor([1, 2, 0, 2])
tensor([2, 2, 3])


In [242]:
a = torch.max(X, dim=0)
print(a.values)
print(a.indices)

tensor([0.6884, 0.9737, 2.3136, 1.4347])
tensor([1, 2, 0, 2])


# autograd(자동미분)
- 자동 미분을 이용해 gradient(미분계수)를 계산하는 pytorch system.
- 머신러닝 모델의 경우 사람의 손으로 미분된 식을 넣어 경사하강법을 적용시켜 주어야 한다.
- 딥러닝 모델에서 weight와 bias tensor들(Parameter)은 backpropagation(역전파)를 이용해 gradient를 구해서 loss가 줄어드는 방향으로 update를 하게된다.
- pytorch는 이런 미분 수행을 자동으로 처리해 준다.
    - gradient(기울기)를 구한다는 것은 미분을 한다는 것을 말한다.
- tensor가 미분 가능하려면(gradient 계산 대상 변수) `requires_grad=True` 로 설정되어 있어야 한다. (default: False)
    - 그래야 처음 결과를 예측하는 Forward 과정에서 gradient를 구하기 위한 도함수를 미리 같이 계산하여 가지고 있을 수 있다.

> - **미분**
>   -  (순간) 변화율을 계산한다.
>   - $$\frac{\partial y}{\partial x}$$
>       - x에 대한 y의 변화율. 즉 x가 변하면 y는 얼마나 변할까?

In [272]:
import torch
x = torch.tensor([1.0], dtype=torch.double, requires_grad=True) # 당연히 attribute 값이니 나중에 바꿔줘도 돼 
print(x.requires_grad, x, x.shape)

True tensor([1.], dtype=torch.float64, requires_grad=True) torch.Size([1])


In [273]:
# Tensor의 Attribute
x.data # 실제 Tensor에 넣어준 '값'
x.grad # Backward에서 계산된 Gradient '값'
x.shape, x.ndim, x.names

(torch.Size([1]), 1, (None,))

In [ ]:
# Tensor 데이터 x 를 다루는 Feature Extracting Function y, 얘도 Tensor야 
y = x ** 2
y, y.grad_fn, y.data, y.grad # requires_grad=True 인 Tensor를 기준으로 함수식이 적용될 때 자동미분이 적용된 함수 -> y에 같이 저장을 해놔
# PowBackward0 : 제곱 연산의 미분을 수행하는 "함수 미분 방식"
# MulBackward0 : 곱셈 연산의 미분을 수행 / 3*x꼴
# AddBackward0 : 여러 미분 함수들을 합침 
# 맨 뒤 숫자는 grad_fn 을 구분하는 index

C:\Users\jinhy\AppData\Local\Temp\ipykernel_15600\3509216560.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  y, y.grad_fn, y.data, y.grad # requires_grad=True 인 Tensor를 기준으로 함수식이 적용될 때 자동미분이 적용된 함수 -> y에 같이 저장을 해놔


(tensor([1.], dtype=torch.float64, grad_fn=<PowBackward0>),
 tensor([1.], dtype=torch.float64),
 None)

In [ ]:
# Gradient 계산
y.backward()
x.grad

tensor([2.], dtype=torch.float64)

In [320]:
'''정리
Tensor로 이루어진 여러 Layer는 각각의 Tensor층을 지나갈 때마다 고유한 계산식을 포함하게 되며,
이 계산식을 통해 이전 Tensor의 미분, Gradient를 계산할 수 있다.
이를 Chain Rule과 함께 활용하여 Parameter에 대한 경사하강법을 진행할 수 있는 것이다. 

연산 그래프의 경우 각 계산값과 연산자를 나타내는 노드와 이들을 연결하는 엣지로 이루어져 있다.
각각의 Tensor 값이 계산값 노드를 의미하며, 만일 어떠한 Tensor 가 다른 Tensor 를 연산식으로써 이용한다면 해당 Tensor의 grad_fn에
    그 연산자를 자동 미분하는 grad_fn 노드(연산자 노드)가 저장된다.
    그 grad_fn 노드는 사용한 Tensor 객체에 대한 정보를 참조하고 있으며, 이때 사용된 함수식을 참조한다.
마지막으로 이들의 참조 관계가 엣지를 이루며, 이 그래프는 여러 Layer에 걸쳐 계승된다. 
'''

'정리\nTensor로 이루어진 여러 Layer는 각각의 Tensor층을 지나갈 때마다 고유한 계산식을 포함하게 되며,\n이 계산식을 통해 이전 Tensor의 미분, Gradient를 계산할 수 있다.\n이를 Chain Rule과 함께 활용하여 Parameter에 대한 경사하강법을 진행할 수 있는 것이다. \n\n연산 그래프의 경우 각 계산값과 연산자를 나타내는 노드와 이들을 연결하는 엣지로 이루어져 있다.\n각각의 Tensor 값이 계산값 노드를 의미하며, 만일 어떠한 Tensor 가 다른 Tensor 를 연산식으로써 이용한다면 해당 Tensor의 grad_fn에\n    그 연산자를 자동 미분하는 grad_fn 노드(연산자 노드)가 저장된다.\n    그 grad_fn 노드는 사용한 Tensor 객체에 대한 정보를 참조하고 있으며, 이때 사용된 함수식을 참조한다.\n마지막으로 이들의 참조 관계가 엣지를 이루며, 이 그래프는 여러 Layer에 걸쳐 계승된다. \n'

In [291]:
a = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([3.2]) # r_grad=False
y = a - b + 3 # grad_fn 정의
y.backward() # grad를 계산 - a에 대해서만 계산 

In [414]:
# 간단한 경사하강법 구현
input_data = torch.tensor([30.2])
output_data = torch.tensor([10.5]) 
weight = torch.tensor([0.2], requires_grad=True) # parameter
y_pred = 3*weight * input_data # 모델 예측값 
loss = 2*(output_data - y_pred)**2 # 오차계산-MSE
# losses = loss * output_data

In [415]:
y_pred, loss, y_pred.grad_fn, loss.grad_fn#, losses.grad_fn

(tensor([18.1200], grad_fn=<MulBackward0>),
 tensor([116.1288], grad_fn=<MulBackward0>),
 <MulBackward0 at 0x130d37dc730>)

In [419]:
print(loss.grad_fn)
print(loss.grad_fn.next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0].next_functions[1][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0].next_functions[1][0].next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0].next_functions[1][0].next_functions[0][0].next_functions[0][0])
print(loss.grad_fn.next_functions[0][0].next_functions[0][0].next_functions[1][0].next_functions[0][0].next_functions[0][0].next_functions)
# print(loss.grad_fn.next_functions[0][0].next_functions[0][0].next_functions[1][0].next_functions[0][0].next_functions[0][0].next_functions[0][0].next_functions)

()


## torch.no_grad() 
- no_grad()를 with 구문에서 연산을 할 경우 with block 내에서 requires_grad=True로 설정된 변수를 이용한 계산식이 있더라도 grad_fn을 생성하지 않는다. 즉 gradient를 계산하지 않는다.
- 딥러닝 모델을 평가 하거나 추론을할 때는 gradient를 계산할 필요가 없기 때문에 no_grad 구문을 사용한다.


In [324]:
x = torch.tensor([1.0], requires_grad=True)
with torch.no_grad():
    y = x**2
    print('결과:', y.data.numpy())
    print('grad_fn:', y.grad_fn)

결과: [1.]
grad_fn: None


## gradient 값 초기화
- backward() 에서 계산되어 저장된 gradient값을 초기화한다.
- 반복 학습을 할 경우 gradient가 누적되는 문제가 발생한다. 그래서 한번 학습이 끝나면 다음 학습 전에 초기화하는 작업을 해야 한다.

In [350]:
x = torch.tensor([1.0], requires_grad=True)
print(x.grad)
y = x**2
z = 2*y**2
z.backward()
print(y.requires_grad)
print(x.grad, y.grad, z.grad)

None
True
tensor([8.]) None None


C:\Users\jinhy\AppData\Local\Temp\ipykernel_15600\124430927.py:7: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  print(x.grad, y.grad, z.grad)


In [351]:
# x.grad = None
t = x**3 # 같은 Tensor를 여러 번 이용할 경우 서로 다른 노드로 사용되어 구성된 연산그래프로 판단해 grad 값을 누적하게 된다.
        # 그래서 초기화가 필요한 것 
t.backward()
print(x.grad) 

tensor([11.])
